name: "Bug report"
labels: ["bug"]
description: "Create a report to help us improve"

body:
  - id: description
    type: textarea
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Description"
    validations:
      required: true
  - id: reproduce-steps
    type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce the behavior:"
      placeholder: >
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - id: expected-behavior
    type: textarea
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Expected behavior"
    validations:
      required: false
  - id: additional-context
    type: textarea
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
      placeholder: "Additional context"
    validations:
      required: false
  - id: terms
    type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
